"use client";

import React from "react";
import Link from "next/link";
import { Home } from "lucide-react";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black flex flex-col items-center justify-start px-6 py-32 relative">
      <div className="absolute top-0 w-full h-[500px] bg-gradient-to-b from-[#00D4FF]/10 to-transparent pointer-events-none" />
      <div className="w-full max-w-4xl mx-auto flex flex-col items-center text-center z-10">
        <h1 className="text-5xl md:text-6xl font-black text-white mb-6 uppercase tracking-tighter">
          Terms of <span className="text-[#00D4FF]">Service</span>
        </h1>
        <p className="text-neutral-400 text-lg mb-12 max-w-2xl">
          By accessing and using our services, you agree to be bound by the following terms.
        </p>
      </div>

      <div className="w-full max-w-4xl mx-auto bg-neutral-900/50 border border-white/5 rounded-2xl p-8 md:p-12 shadow-2xl z-10 text-neutral-300 space-y-8">
        <section>
          <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
          <p className="leading-relaxed">
            By engaging XeonSec for strategy, ML intelligence, or cybersecurity services, you agree to comply with all applicable laws and these Terms of Service. If you do not agree with any of these terms, you are prohibited from using our services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">2. Intellectual Property</h2>
          <p className="leading-relaxed">
            All original content, features, and technical architecture generated by XeonSec remain the intellectual property of XeonSec until full payment is received, at which point ownership transfers entirely as outlined in your specific project agreement.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">3. Limitation of Liability</h2>
          <p className="leading-relaxed">
            While we build systems with zero-compromise technical precision, XeonSec shall not be held liable for any indirect, incidental, or consequential damages resulting from the use or inability to use our deliverables.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">4. Governing Law</h2>
          <p className="leading-relaxed">
            These Terms shall be governed and construed in accordance with the laws of the applicable jurisdiction, without regard to its conflict of law provisions.
          </p>
        </section>

        <div className="pt-8 border-t border-white/10 mt-12 flex justify-center pb-8">
          <Link href="/" className="text-[#00D4FF] hover:text-white transition-all duration-300 p-4 rounded-full bg-neutral-900 border border-white/5 hover:border-[#00D4FF]/30 shadow-[0_4px_14px_rgba(0,0,0,0.5)] hover:shadow-[0_0_20px_rgba(0,212,255,0.2)] hover:-translate-y-1">
            <Home size={24} />
          </Link>
        </div>
      </div>
    </main>
  );
}
